### PR TITLE
Observable for SocketIO Client connection

### PR DESCRIPTION
**Pull request by AmirCuric**

### CODE REVIEW

**Review by mtfranchetto — CHANGES_REQUESTED** [review]
Test do not pass (see Travis). Moreover, an Error object should be passed to the onError calls.

**Comment by AmirCuric** [comment]
True! The disconnected status was put there by mistake.

**Review by mtfranchetto — CHANGES_REQUESTED** [review]
Great, but the combineLatest could be simplified with a simple flatMap().take(1).

**Comment by AmirCuric** [comment]
Done.

**Pull request merged**
